name: auto-generate-gitbook
on: # 在 mac 分支上进行 push 时触发
  push:
    branches:
      - mac

jobs:
  mac-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: checkout mac
        uses: actions/checkout@v2
        with:
          ref: mac

      - name: install nodejs
        uses: actions/setup-node@v1

      - name: configue gitbook
        run: |
          npm install -g gitbook-cli
          gitbook install
          npm install -g gitbook-summary

      - name: generate _book folder
        run: |
          gitbook build

      - name: push _book to branch gh-pages
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REF: github.com/${{github.repository}}
          MYEMAIL: zhugelianglongming@163.com
          MYNAME: ${{github.repository_owner}}
        run: |
          cd _book
          git config --global user.email "${MYEMAIL}"
          git config --global user.name "${MYNAME}"
          git init
          git remote add origin https://${REF}
          git add .
          git commit -m "Updated By Github Actions With Build ${{github.run_number}} of ${{github.workflow}} For Github Pages"
          git branch -M mac
          git push --force --quiet "https://${TOKEN}@${REF}" mac:gh-pages

# ref:
# - https://github.com/wangzhebufangqi/auto-export-gitbook